#ifndef CONFIG_H
#define CONFIG_H

#define ONE_WIRE_BUS 2
#define TEMPERATURE_PRECISION 12
#define READ_INTERVAL_MS 2000
#define MAX_RETRIES 3
#define MAX_CONSECUTIVE_FAILURES 5
#define OUTPUT_FORMAT_JSON false
#define SERIAL_BAUD 115200

#endif